@section('topbar_title', 'Buat ' . ($isPractice ? 'Latihan' : 'Quiz') . ' Baru')
<x-app-layout><div class="max-w-2xl mx-auto space-y-6"><div><a href="{{ route($isPractice ? 'practices.index' : 'quizzes.index', $course) }}" class="text-xs font-bold text-slate-500">← Kembali</a><h1 class="text-xl font-bold text-slate-800 mt-2">Buat {{ $isPractice ? 'Latihan' : 'Quiz' }} Baru</h1></div>
<form action="{{ route($isPractice ? 'practices.store' : 'quizzes.store', $course) }}" method="POST" class="bg-white rounded-2xl border border-slate-100 shadow-sm p-6 space-y-5">@csrf
<div><label class="block text-xs font-semibold mb-1">Judul *</label><input name="title" required value="{{ old('title') }}" class="w-full border rounded-xl px-3 py-2.5 text-sm"></div>
<div><label class="block text-xs font-semibold mb-1">Deskripsi</label><textarea name="description" rows="2" class="w-full border rounded-xl px-3 py-2.5 text-sm">{{ old('description') }}</textarea></div>
<div><label class="block text-xs font-semibold mb-1">Chapter *</label><select name="chapter_id" class="w-full border rounded-xl px-3 py-2.5 text-sm" {{ $isPractice ? 'required' : '' }}><option value="">{{ $isPractice ? '-- Pilih chapter --' : '-- Final Quiz (tanpa chapter) --' }}</option>@foreach($chapters as $chapter)<option value="{{ $chapter->id }}" @selected(old('chapter_id') == $chapter->id)>{{ $chapter->order }}. {{ $chapter->title }}</option>@endforeach</select><p class="text-xs text-slate-400 mt-1">{{ $isPractice ? 'Latihan selalu ditempatkan pada chapter.' : 'Kosongkan untuk Final Quiz.' }}</p></div>
@unless($isPractice)<div><label class="block text-xs font-semibold mb-1">Nilai Kelulusan (%) *</label><input type="number" name="passing_score" required min="1" max="100" value="{{ old('passing_score', 70) }}" class="w-full border rounded-xl px-3 py-2.5 text-sm"></div><div><label class="block text-xs font-semibold mb-1">Timer (menit)</label><input type="number" name="time_limit" min="1" max="300" value="{{ old('time_limit') }}" class="w-full border rounded-xl px-3 py-2.5 text-sm"></div><div><label class="block text-xs font-semibold mb-1">Kebijakan hasil *</label><select name="review_policy" class="w-full border rounded-xl px-3 py-2.5 text-sm"><option value="show_all">Tampilkan semua</option><option value="points_only">Skor saja</option><option value="hide_all">Sembunyikan detail</option></select></div>@else<input type="hidden" name="review_policy" value="show_all">@endunless
<div><label class="block text-xs font-semibold mb-1">Maks. percobaan {{ $isPractice ? '(kosong = tanpa batas)' : '*' }}</label><input type="number" name="max_attempts" {{ $isPractice ? '' : 'required' }} min="1" max="{{ $isPractice ? 100 : 10 }}" value="{{ old('max_attempts', $isPractice ? '' : 1) }}" class="w-full border rounded-xl px-3 py-2.5 text-sm"></div>
<div class="flex gap-4 text-xs"><label><input type="checkbox" name="shuffle_questions" value="1"> Acak soal</label><label><input type="checkbox" name="shuffle_options" value="1"> Acak pilihan</label><label><input type="checkbox" name="is_active" value="1" checked> Aktif</label></div>
@if($errors->any())<div class="text-xs text-red-600">{{ $errors->first() }}</div>@endif<button class="w-full py-2.5 bg-blue-600 text-white rounded-xl text-sm font-semibold">Simpan & Pilih Soal</button></form></div></x-app-layout>
