<?php

$filePath = '/Applications/XAMPP/xamppfiles/htdocs/LMS-Garbarata/lang/en.json';
$data = json_decode(file_get_contents($filePath), true);

$allMasterKeys = [
    // General & Navigation
    "Beranda" => "Dashboard",
    "Kalender" => "Calendar",
    "Kelola Pengguna" => "Manage Users",
    "Kelola Materi" => "Manage Materials",
    "Kelola Latihan" => "Manage Exercises",
    "Kelola Quiz dan Ujian" => "Manage Quizzes and Exams",
    "Materi Garbarata" => "Garbarata Course",
    "Latihan" => "Exercises",
    "Quiz & Ujian" => "Quizzes & Exams",
    "Sertifikat" => "Certificates",
    "Laporkan konten tidak aman" => "Report unsafe content",
    "Sertifikat Belum Tersedia" => "Certificate Not Available Yet",
    "Silakan selesaikan semua quiz dengan nilai kelulusan terlebih dahulu!" => "Please complete all quizzes with a passing score first!",
    "Peserta" => "Participant",
    "Instruktur" => "Instructor",
    "Administrator" => "Administrator",
    "keluar" => "Logout",
    "Pilih Bahasa" => "Select Language",
    "Bahasa Indonesia" => "Indonesian Language",
    "Bahasa Inggris" => "English Language",
    "Yakin ingin keluar?" => "Are you sure you want to exit?",
    "Anda akan keluar dari sesi masuk LMS-Garbarata saat ini." => "You are about to log out of the current LMS-Garbarata session.",
    "Batal" => "Cancel",

    // Quiz Management & Attempts
    "Hasil Quiz Peserta" => "Participant Quiz Results",
    "Hasil Latihan Peserta" => "Participant Exercise Results",
    "Kembali ke Manajemen Quiz" => "Back to Quiz Management",
    "Kembali ke Manajemen Latihan" => "Back to Exercise Management",
    "Manajemen Quiz" => "Quiz Management",
    "Manajemen Latihan" => "Practice Management",
    "Buat Quiz Baru" => "Create New Quiz",
    "Buat Latihan Baru" => "Create New Practice",
    "Klik tombol \"Nilai Jawaban\" di bawah untuk mulai menilai jawaban peserta." => "Click the \"Grade Answers\" button below to start grading participant answers.",
    "percobaan menunggu penilaian esai" => "attempts awaiting essay grading",
    "Belum ada peserta yang mengerjakan quiz ini." => "No participants have attempted this quiz yet.",
    "Belum ada peserta yang mengerjakan latihan ini." => "No participants have attempted this exercise yet.",
    "Apakah Anda yakin ingin mereset percobaan ini? Nilai & jawaban akan dihapus." => "Are you sure you want to reset this attempt? The score and answers will be deleted.",
    "Ekspor Rekap Nilai (CSV)" => "Export Grade Summary (CSV)",

    // Quiz Result Page & Badges
    "Menunggu Penilaian Instruktur" => "Awaiting Instructor Grading",
    "Jawaban esai kamu sedang menunggu untuk dinilai oleh instruktur. Nilai akhir kamu akan keluar setelah semua soal esai selesai dinilai. Kamu bisa cek kembali halaman ini nanti." => "Your essay answers are awaiting grading by the instructor. Your final score will be released after all essay questions have been graded. You can check back on this page later.",
    "Sertifikat Diterbitkan!" => "Certificate Issued!",
    "Kamu telah menyelesaikan semua quiz dalam course ini. Sertifikatmu sudah siap!" => "You have completed all quizzes in this course. Your certificate is ready!",
    "Lihat Sertifikat" => "View Certificate",
    "Soal" => "Question",
    "poin" => "pts",
    "Gambar Soal" => "Question Image",
    "Jawabanmu:" => "Your Answer:",
    "Jawabanmu (Mencocokkan):" => "Your Answer (Matching):",
    "Jawabanmu (Urutan Langkah):" => "Your Answer (Step Order):",
    "Tidak dijawab" => "Not answered",
    "Tidak diisi" => "Not answered",
    "Penilaian Instruktur" => "Instructor Evaluation",
    "Dinilai oleh" => "Graded by",
    "Belum dinilai oleh instruktur" => "Not graded by instructor yet",
    "Langkah" => "Step",
    "Seharusnya:" => "Should be:",
    "Jawaban benar:" => "Correct answer:",
    "Penjelasan:" => "Explanation:",

    // Grade Essay Page
    "Bagian 1: Soal Esai (Perlu Penilaian Manual)" => "Section 1: Essay Questions (Manual Grading Required)",
    "Bagian 2: Soal Non-Esai (Penilaian Otomatis)" => "Section 2: Non-Essay Questions (Automatic Grading)",
    "Esai" => "Essay",
    "Soal:" => "Question:",
    "Jawaban Peserta:" => "Participant Answer:",
    "(tidak ada jawaban)" => "(no answer)",
    "(tidak menjawab)" => "(did not answer)",
    "(kosong)" => "(empty)",
    "(opsi terhapus)" => "(deleted option)",
    "(tidak diisi)" => "(not filled)",
    "Nilai" => "Score",
    "Feedback" => "Feedback",
    "(opsional)" => "(optional)",
    "Tulis komentar atau feedback untuk peserta..." => "Write a comment or feedback for the participant...",
    "Sebelumnya dinilai" => "Previously graded",
    "oleh" => "by",
    "Nilai lama:" => "Previous score:",
    "Pilihan Ganda" => "Multiple Choice",
    "Benar / Salah" => "True / False",
    "Mencocokkan" => "Matching",
    "Mengurutkan" => "Ordering",
    "Lainnya" => "Other",
    "Salah / Parsial" => "Incorrect / Partial",
    "Poin didapat:" => "Points earned:",
    "Kunci Jawaban Benar:" => "Correct Answer Key:",

    // Start Page & Modals
    "Latihan Chapter" => "Chapter Practice",
    "Ujian — Ujian Akhir" => "Exam — Final Exam",
    "Questions" => "Questions",
    "Waktu" => "Time",
    "Tanpa Batas Nilai" => "No Passing Mark",
    "Nilai Lulus" => "Passing Mark",
    "Sisa Percobaan" => "Remaining Attempts",
    "Percobaan Terakhir: Skor" => "Last Attempt: Score",
    "Perhatikan sebelum mulai:" => "Please note before starting:",
    "Jawaban tersimpan otomatis." => "Answers are saved automatically.",
    "Percobaan tanpa batas." => "Unlimited attempts.",
    "Latihan dapat ditinggalkan lalu dilanjutkan kembali, dan tidak memengaruhi progres atau sertifikat." => "Practice can be left and resumed later, and does not affect progress or certificate.",
    "Nilai kelulusan minimum:" => "Minimum passing mark:",
    "Latihan Lagi" => "Try Practice Again",
    "Mulai Latihan" => "Start Practice",
    "Coba Lagi" => "Try Again",
    "Mulai Quiz" => "Start Quiz",
    "Batas Percobaan Habis" => "No Remaining Attempts",
    "Jadwal Akses Quiz" => "Quiz Access Schedule",
    "Dibuka:" => "Opens at:",
    "Ditutup:" => "Closes at:",

    // Attempt Page & Anti-Cheat
    "Tulis jawaban esai kamu di bawah ini. Jawaban akan dinilai oleh instruktur." => "Write your essay response below. Answers will be evaluated by the instructor.",
    "Tuliskan jawaban kamu di sini..." => "Write your answer here...",
    "Pilih Pasangan" => "Select Match",
    "Pilih Langkah Ke-" => "Select Step ",
    "Sudah dijawab (Abu-abu)" => "Answered (Gray)",
    "Ragu-ragu / Ditandai (Oranye)" => "Flagged (Orange)",
    "Belum dijawab (Putih)" => "Unanswered (White)",
    "Sedang Dikerjakan" => "In Progress",
    "Yakin submit quiz?" => "Are you sure you want to submit?",
    "soal belum terjawab. Soal yang belum dijawab tidak akan mendapat poin." => "questions unanswered. Unanswered questions will receive no points.",
    "Semua soal sudah dijawab." => "All questions have been answered.",
    "Ya, Submit" => "Yes, Submit",
    "Peringatan Keamanan!" => "Security Warning!",
    "Pelanggaran Keamanan" => "Security Violation",
    "Quiz Anda otomatis dikirim karena melanggar aturan fokus halaman quiz sebanyak 3 kali." => "Your quiz was automatically submitted because you left the quiz page 3 times.",
    "Anda terdeteksi meninggalkan halaman quiz." => "You were detected leaving the quiz page.",
    "Mengerti & Lanjutkan" => "Understood & Continue",
    "Peringatan" => "Warning",
    "Harap tetap fokus pada halaman quiz. Jika Anda meninggalkan halaman ini sebanyak" => "Please stay focused on the quiz page. If you leave this page",
    "kali lagi, jawaban Anda akan otomatis dikirim secara paksa!" => "more time(s), your answers will be automatically submitted!",
    "Koneksi Terhubung Kembali! Menyelaraskan jawaban..." => "Connection Restored! Syncing answers...",
    "Koneksi Internet Terputus! Harap jangan menutup halaman quiz ini. Jawaban Anda akan otomatis tersinkronisasi kembali ketika internet aktif." => "Internet Connection Lost! Please do not close this quiz page. Your answers will automatically sync when internet is restored.",
    "kosong = tanpa batas" => "empty = unlimited",
    "Maks. percobaan (kosong = tanpa batas)" => "Max attempts (empty = unlimited)"
];

foreach ($allMasterKeys as $k => $v) {
    $data[$k] = $v;
}

$cleanJson = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
file_put_contents($filePath, $cleanJson);

echo "Successfully merged ALL master translation keys into lang/en.json! Total keys: " . count($data) . "\n";
